# This is the network config written by 'subiquity'
network:
  ethernets:
    eno1:
      dhcp4: true
    eno2:
      dhcp4: true
    enp129s0:
      dhcp4: true
      routes:
      - to: 239.168.40.0/24
    enp1s0:
      dhcp4: true
  version: 2
