# This is the network config written by 'subiquity'
network:
  ethernets:
    eno1:
      dhcp4: true
    eno2:
      dhcp4: true
    enp129s0np0:
      dhcp4: true
      routes:
      - to: 239.168.40.128/25
    enp1s0np0:
      dhcp4: true
      routes:
      - to: 239.168.40.0/25
  version: 2
