# This is the network config written by 'subiquity'
network:
  ethernets:
    eno1:
      dhcp4: false
      addresses: [10.1.3.10/24]
      gateway4: 10.1.3.204
      nameservers:
        addresses: [146.88.1.4,8.8.8.8]
    eno2:
      dhcp4: false
      addresses: [169.254.128.1/24]
    enp129s0np0:
      dhcp4: false
      addresses: [192.168.40.10/25]
      mtu: 9000
      routes:
      - to: 239.168.40.0/24
    enp1s0np0:
      dhcp4: false
      addresses: [192.168.40.210/25]
      mtu: 9000
  version: 2
